sonar.projectKey=usdot-jpo-ode-1_jpo-cvdp
sonar.organization=usdot-jpo-ode-1
sonar.sources=src,cv-lib/src
sonar.exclusions=src/ppm.cpp
sonar.cfamily.build-wrapper-output=bw-output
sonar.projectBaseDir=/home/runner/work/jpo-cvdp/jpo-cvdp
sonar.host.url=https://sonarcloud.io
sonar.cfamily.gcov.reportsPath=/coverage/
sonar.coverageReportPaths=coverage/coverage.xml
# Set Git as SCM sensor
sonar.scm.disabled=false
sonar.scm.enabled=true
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=.cpp,.h,.tpp