name: CI
on: 
  pull_request:
  push:
    
jobs:
  cvdp:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout ${{ github.event.repository.name }}
       uses: actions/checkout@v3           
     - name: Install deps
       run: | 
         git clone https://github.com/edenhill/librdkafka.git
         cd librdkafka
         ./configure
         make
         sudo make install
         cd ..  
     - name: Build cvdp c++ source code
       uses: nicledomaS/cmake_build_action@v1.4
       with:
         submodule_update: OFF
         run_tests: ON
         unit_test_build: -Dtest=ON
         config: RELEASE
     - name: Archive artifacts results
       uses: actions/upload-artifact@v3
       with:
         name: cvdp
         path: build/*.tar.gz 
         if-no-files-found: error

  cvdp_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-coverage python3-pip python3-pytest 
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages
          cd $GITHUB_WORKSPACE/docker-test/
          python3 -m coverage run -m pytest
          python3 -m coverage xml --omit="/opt/*,/root/*,/tmp/*,/usr/*,/var/*,**/__init__.py"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: carma-cloud-bridge-coverage
          path: docker-test/test/coverage.xml
          if-no-files-found: error

  sonar:
    needs: [cvdp, cvdp_python]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      - run: chmod +x -R /home/runner/work/jpo-cvdp/jpo-cvdp
      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: cvdp
          path: docker-test/test/coverage.xml
      - name: Find coverage.xml
        shell: bash
        run: |
          find "$GITHUB_WORKSPACE" -name "coverage.xml"                
      - name: Setup SonarScanner
        uses: warchant/setup-sonar-scanner@v4
        with:
          version: 4.8.0.2856
      - name: Generate sonar properties file
        run: |
          cat <<EOF > /tmp/sonar-scanner.properties
          sonar.host.url=https://sonarcloud.io
          sonar.projectBaseDir=$GITHUB_WORKSPACE
          sonar.projectKey=usdot-jpo-ode_jpo-security-svcs
          sonar.organization=usdot-jpo-ode-1
          sonar.python.coverage.reportPaths=$GITHUB_WORKSPACE/docker-test//test/coverage.xml
          sonar.python.version=3.9
          sonar.sources=.
          EOF
      - name: Run SonarScanner
        uses: usdot-fhwa-stol/actions/sonar-scanner@main
        with:
          sonar-properties-path: /tmp/sonar-scanner.properties
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          working-dir: $GITHUB_WORKSPACE                 
