name: DockerHub Build and Push

on:
  push:
    branches: [ master, develop, release/*, feature/update_docker_workflows ]
  workflow_dispatch:

jobs:
  publish:
    uses: usdot-jpo-ode/actions/.github/workflows/dockerhub.yml@main
    with:
      image: saikrishnabairamoni/v2xhub
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:   ${{ secrets.DOCKERHUB_TOKEN }}
