name: cvdp
on: 
 workflow_dispatch:
    
jobs:
  cvdp:
   runs-on: ubuntu-latest
   container:
    image: ubuntu:jammy-20230126
    env:
      DEBIAN_FRONTEND: noninteractive
      INIT_ENV: "/home/jpo-cvdp/.base-image/init-env.sh"
      SONAR_SCANNER_VERSION: "4.6.2.2472"
      REDACTION_PROPERTIES_PATH: "/__w/jpo-cvdp/jpo-cvdp/config/fieldsToRedact.txt"
      BUILD_WRAPPER_OUT_DIR: "/__w/jpo-cvdp/jpo-cvdp/bw-output"
      TERM: xterm
    options: "--user root"
   steps:
     - name: Checkout ${{ github.event.repository.name }}
       uses: actions/checkout@v3   
       with:
        fetch-depth: 0
     - name: Install Latest Docker
       run: |
         apt update
         apt-get -y install sudo wget curl gnupg lsb-release gcovr
         sudo apt-get -y install software-properties-common
         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
         sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
         #curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
         sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
         chmod +x /usr/local/bin/docker-compose
         sudo apt-get -y update
         sudo apt-get -y install docker-ce
     - name: Check Docker Version
       run: docker --version && docker-compose version
     - name: install g++
       run: |
         sudo apt-get -y install build-essential
         sudo apt -y install cmake g++ libprotobuf-dev protobuf-compiler
         sudo apt -y install apt-transport-https ca-certificates curl software-properties-common
         export CXX="g++"
     - name: install librdkafka
       run: |
         git clone --depth 1 https://github.com/confluentinc/librdkafka.git /home/jpo-cvdp/ext/librdkafka
         cd /home/jpo-cvdp/ext/librdkafka/
         cmake -H. -B_cmake_build
         cmake --build _cmake_build
         cmake --build _cmake_build --target install
     - name: Install Sonar
       run: |
         SONAR_DIR=/__w/jpo-cvdp/jpo-cvdp/sonarqube
         mkdir $SONAR_DIR
         curl -o $SONAR_DIR/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux.zip
         curl -o $SONAR_DIR/build-wrapper.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
         curl -sL https://deb.nodesource.com/setup_16.x |bash -
         apt-get install -y nodejs unzip
         cd $SONAR_DIR
         for ZIP in *.zip; do
         unzip "$ZIP" -d .
         rm "$ZIP"
         done
         mv $(ls $SONAR_DIR |grep "sonar-scanner-") $SONAR_DIR/sonar-scanner/
         mv $(ls $SONAR_DIR |grep "build-wrapper-") $SONAR_DIR/build-wrapper/
         echo $SONAR_DIR/sonar-scanner/bin >> $GITHUB_PATH
         echo $SONAR_DIR/build-wrapper >> $GITHUB_PATH         
     - name: Install sonar-scanner and build-wrapper
       uses: SonarSource/sonarcloud-github-c-cpp@v1
     - name: Run build-wrapper
       run: |
         ls -la && pwd 
         chmod   755  -R /__w/jpo-cvdp/jpo-cvdp
         export LD_LIBRARY_PATH=/usr/local/lib
         build-wrapper-linux-x86-64 --out-dir $BUILD_WRAPPER_OUT_DIR ./build_and_run_unit_tests.sh
     - name: Run sonar-scanner
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       run: |
         sonar-scanner --define sonar.cfamily.build-wrapper-output= "$BUILD_WRAPPER_OUT_DIR"
