name: cvdp
on: 
 workflow_dispatch:
    
jobs:
  cvdp:
   runs-on: ubuntu-latest
   container:
    image: ubuntu:jammy-20230126
    env:
      DEBIAN_FRONTEND: noninteractive
      INIT_ENV: "/home/jpo-cvdp/.base-image/init-env.sh"
      SONAR_SCANNER_VERSION: "4.6.2.2472"
      TERM: xterm
    options: "--user root"
   steps:
     - name: Checkout ${{ github.event.repository.name }}
       uses: actions/checkout@v3   
     - name: install docker     
       uses: docker-practice/actions-setup-docker@master
       timeout-minutes: 12
     - run: |
         set -x        
         apt update
         apt-get -y install sudo curl
         sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
         sudo rm /usr/local/bin/docker-compose
         curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
         chmod +x docker-compose
         sudo mv docker-compose /usr/local/bin
         sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
         sudo apt-get update -qq
     - name: install g++
       run: |
         sudo mkdir gcc-4.9-deb && cd gcc-4.9-deb
         sudo wget http://launchpadlibrarian.net/247707088/libmpfr4_3.1.4-1_amd64.deb
         sudo wget http://launchpadlibrarian.net/253728424/libasan1_4.9.3-13ubuntu2_amd64.deb
         #sudo wget http://launchpadlibrarian.net/253728426/libgcc-4.9-dev_4.9.3-13ubuntu2_amd64.deb
         sudo wget http://launchpadlibrarian.net/253728314/gcc-4.9-base_4.9.3-13ubuntu2_amd64.deb
         sudo wget http://launchpadlibrarian.net/253728399/cpp-4.9_4.9.3-13ubuntu2_amd64.deb
         sudo wget http://launchpadlibrarian.net/253728404/gcc-4.9_4.9.3-13ubuntu2_amd64.deb
         sudo wget http://launchpadlibrarian.net/253728432/libstdc++-4.9-dev_4.9.3-13ubuntu2_amd64.deb
         sudo wget http://launchpadlibrarian.net/253728401/g++-4.9_4.9.3-13ubuntu2_amd64.deb
         sudo dpkg -i gcc-4.9-base_4.9.3-13ubuntu2_amd64.deb
         sudo dpkg -i libmpfr4_3.1.4-1_amd64.deb
         sudo dpkg -i libasan1_4.9.3-13ubuntu2_amd64.deb
         #sudo dpkg -i libgcc-4.9-dev_4.9.3-13ubuntu2_amd64.deb
         sudo dpkg -i cpp-4.9_4.9.3-13ubuntu2_amd64.deb
         sudo dpkg -i gcc-4.9_4.9.3-13ubuntu2_amd64.deb
         sudo dpkg -i libstdc++-4.9-dev_4.9.3-13ubuntu2_amd64.deb
         sudo dpkg -i g++-4.9_4.9.3-13ubuntu2_amd64.deb
         export CXX="g++-4.9"
     - name: install librdkafka
       run: |
         git clone --depth 1 https://github.com/confluentinc/librdkafka.git /home/jpo-cvdp/ext/librdkafka
         cd /home/jpo-cvdp/ext/librdkafka/
         cmake -H. -B_cmake_build
         cmake --build _cmake_build
         cmake --build _cmake_build --target install
         sudo git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure
         make
         sudo make install
         cd ..
         sudo mkdir /tmp/build
         sudo cd /tmp/build
         sudo cmake $$GITHUB_WORKSPACE
         sudo export LD_LIBRARY_PATH=/usr/local/lib
     - name: build
       run: 
         build-wrapper-linux-x86-64 --out-dir $$GITHUB_WORKSPACE/bw-output make
         clean all
         ./ppm_tests
         cd $$GITHUB_WORKSPACE
         mkdir coverage
         cd coverage
     - run:
         gcov $GITHUB_WORKSPACE/cv-lib/src/*.cpp --object-directory
         /tmp/build/cv-lib/CMakeFiles/CVLib.dir/src/
     - run: 
         gcov $$GITHUB_WORKSPACE/src/*.cpp --object-directory
         /tmp/build/CMakeFiles/ppm_tests.dir/src/
     - run: cd $$GITHUB_WORKSPACE
     - run: sonar-scanner
